### ISSUE TITLE
 ESCキーを押すと画面が固まる

### ISSUE THREAD

**Issue by jinbei** [shiromofufactory/pyxel-sangokushi-guide#1]
PC版でプレイし、少なくともシナリオ1の勢力の選択画面でESCキーを押すと画面が固まりました。その後、何を押しても反応ありませんでした。はじめに表示される画面でも同様の事象が発生しました。

**Comment by shiromofufactory** [comment]
こちらはバグではなくEscキーを押すとゲーム終了する仕様によるものなのですが、たしかに不用意に押してしまうこともあると思いましたので、反応しないように修正いたしました。

**Comment by jinbei** [comment]
対応ありがとうざいました。
