### ISSUE TITLE
最初にデモ画面を選択しても、デモが開始されない

### ISSUE THREAD

**Issue by jinbei** [shiromofufactory/pyxel-sangokushi-guide#2]
最初の画面で、4を押してデモを選択しても、そのままの状態となりデモが開始されないようです。

**Comment by shiromofufactory** [comment]
試しましたが普通に開始しますね。
どのように「開始されない」かがわからないので、可能であればGIF動画などをいただければ助かります。
本来なら4を押すと、次にシナリオ選択画面が表示されます。

**Comment by jinbei** [comment]
4を選択しても、画面が遷移しないままとなりますが、何か操作を間違えてますでしょうか？

**Comment by shiromofufactory** [comment]
操作は間違えていないと思いますが、環境依存なのでこちらで確認できないのです。
以下のような操作キャプチャを提供いただけますか？

![SS 2024-04-08 21 04 05](https://github.com/shiromofufactory/pyxel-sangokushi-guide/assets/53714664/e875b14a-daa6-49d6-964e-9a3f0ca54e6e)

**Comment by jinbei** [comment]
ブラウザの環境は以下でした。

Google Chrome
バージョン: 123.0.6312.106（Official Build） （64 ビット）

![スクリーンショット (34)](https://github.com/shiromofufactory/pyxel-sangokushi-guide/assets/1067141/5226477a-b7ca-401d-8876-eaa9e8e6cb4c)

**Comment by shiromofufactory** [comment]
ようやくわかりました。
直近の修正により、セーブデータがない場合にデモモードを選択できない状態となっていました。
（アプリ版では発生せず、PC版のみ。）
ありがとうございました。修正済みです。

**Comment by jinbei** [comment]
修正ありがとうざいました。セーブデータなしでデモモードの開始されるようになりました。
